SELECT a.author_id,b.author_name,a.category,sum(a.price*c.sales) as total_sales
FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE LIKE '2022-01%'
group by AUTHOR_ID,category
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

# SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
# FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
# JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
# WHERE C.SALES_DATE LIKE '2022-01%'
# GROUP BY AUTHOR_ID, CATEGORY
# ORDER BY AUTHOR_ID ASC, CATEGORY DESC;